### PR TITLE
Add a setting to exclude widgets from available widgets

### PR DESCRIPTION
**Pull request by Tilley**

### CODE REVIEW

**Comment by roadsideseb** [comment]
Thanks for that. It's less intrusive than what I had in mind so much better for compatibility. Appreciate it.

**Comment by roadsideseb** [comment]
I also pushed the change to the `releases/0.1` branch.

**Comment by roadsideseb** [comment]
I made a small alteration to the settings and added documentation and a test as well. Instead of the name given to the widget the setting now uses the actual class name to exclude it. This will not cause any issues with translations as `subclass.name` is a translatable string.

**Comment by Tilley** [comment]
Yea sounds better than using name. Will it be the fully qualified class name, including module path?

**Comment by roadsideseb** [comment]
No, just the class name itself, e.g. `FANCYPAGES_WIDGET_EXCLUDES = ['TextWidget']` to exclude the text widget. This should be sufficient for the widgets since it's not a good idea to have widget models with the same class name, you'll be running into naming issues with the tables if you are not namespacing correctly. I'd advise not to use existing class names.

**Pull request merged**
